version: '3'

services:

# Hadoop cluster
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    ports:
     - "8020:8020"
    networks: 
     - hdfs-network
    volumes:
     - hadoop_namenode:/hadoop/dfs/name
    environment:
     - CLUSTER_NAME=test
    env_file:
     - ./hadoop.env
  
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode1
    networks: 
     - hdfs-network
    depends_on:
     - namenode
    volumes:
     - hadoop_datanode1:/hadoop/dfs/data
    env_file:
     - ./hadoop.env
  
  datanode2:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode2
    networks: 
     - hdfs-network
    depends_on:
     - namenode
    volumes:
     - hadoop_datanode2:/hadoop/dfs/data
    env_file:
     - ./hadoop.env
  
  datanode3:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode3
    networks: 
     - hdfs-network
    depends_on:
     - namenode
    volumes:
     - hadoop_datanode3:/hadoop/dfs/data
    env_file:
     - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:

networks:
  hdfs-network:
    driver: bridge
