version: '3'

services:

# Spark speed layer
  spark-worker:
    build: ./stream-data-processing
    command: start-spark worker spark-master
    networks: 
      - kafka_kafka-network
      - hdfs_hdfs-network
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    links:
      - spark-master
    deploy:
      replicas: 2

