version: '3'

services:

# OpenTSDB, serving layer
  opentsdb:
    container_name: opentsdb
    build: ./opentsdb-docker
    external_links: 
      - namenode
    environment:
      - WAITSECS=30
    networks: 
     - hdfs_hdfs-network
     - serv-network
    ports:
      - '4242:4242'
      - '60030:60030'
    volumes:  
      - "./data-serving/hbase-site.xml:/opt/hbase/conf/hbase-site.xml"
      - "./data-serving/opentsdb.conf:/etc/opentsdb/opentsdb.conf"
      - "./data-serving/rollup_config.json:/etc/opentsdb/rollup_config.json"
        
# Dashboard
  grafana:
    image: grafana/grafana
    user: "root"  
    networks:
      - serv-network
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
        
# Conf

networks:
  serv-network:
    driver: bridge
  hdfs_hdfs-network:
    external: true
