#!/usr/bin/env bash
set -x

if [[ "${1}" = 'master' ]]; then
  # Start Hadoop NameNode
  nohup ~/anaconda3/bin/jupyter notebook --ip=0.0.0.0 --allow-root >> /var/log/jupyter &
  sleep 5
  cat /var/log/jupyter
  /usr/local/spark-2.4.3/sbin/start-master.sh
  sleep infinity
elif [[ "${1}" = 'worker' ]]; then
  # Wait for the Spark Master/Hadoop Namenode to start
  while ! nc -vz $2 7077 ; do
    sleep 2;
  done;
  /usr/local/spark-2.4.3/sbin/start-slave.sh spark://$2:7077
  sleep infinity
else
  echo "Invalid command '${1}'" >&2
  exit 1
fi
